name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }}
          if_key_exists: fail
      - name: connect ssh and install pm2
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} sudo apt install nodejs
      - name: delete session
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} node -v
#         run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} cd ${{ secrets.REMOTE_TARGET }}
#       - name: Git pull
#         run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.REMOTE_TARGET }} && git pull"
#       - name: PM2 START
#         run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.REMOTE_TARGET }} && pm2 start npm --name "gitlab-bot" -- start"
